---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker_convenience_script"
      include_role:
        name: "mivek.docker-convenience-script"
      vars:
        install_test_version: true
