---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker_convenience_script"
      include_role:
        name: "docker_convenience_script"
      vars:
        install_test_version: true
